language: node_js
node_js:
- stable
sudo: false
script: travis_retry npm test
env:
  global:
  - secure: Tj8fcY4Pig7i38wVncEF4RAgn7i786qwiFYeog94oSllsmJsCvQ61Qco9Yg8Xr4fDcOIRI8xz6AsB8Z4kuGfgywbOlvCiVEC1qqJpOG490e0OOrvrPR1YToSW1DsLFsnb381CiP9FadOOUx3COMjmJvKR+4kYoJGiRJrpDF5PVA=
  - secure: MssON602wZqWuCeEcZHROyKI7YkkBUOHTF54Qsh41wR7EhBqG+EuU67SUp8RCX3e+aiID0mKCD6+C43c0uEMrdAk0fdPlG6MiQX8dfbq1V7MgIMf8DT2xw0bXt3xrw3bBBsR4Fa6XB6At1VlLmswj1lqGyWvLwTkykSJSTnPrYI=
  - secure: Jh+ZAYimpwDokeuni8ywLIdPyt6Z8PTxdPdHGY5fD4dsRUUc5+eTtu4HKeywzLm/X7Oy17MCC+JK/RCO8LjiQK7M+6Fw+NLkpEgIjJ83MfBBOb8QE9yHWWCpdCNf+V5ZxrEhw0G0wlk0cSMRYbxvsmidDPtfbwy3l9FEC6Qgx1s=
branches:
  only:
  - master
